Repository WebBreacher/WhatsMyName, pull requests merged in 2020-10, with the labels that each got.

#206 Add A Cloud Guru
  web_accounts_list.json
Labels: hacktoberfest-accepted, new site(s)

#207 Change "themeforset" to "themeforest"
  web_accounts_list.json
Labels: bug, hacktoberfest-accepted

#213 Fixes #209 + removed Scribd since the config was for scratch.
  web_accounts_list.json
Labels: hacktoberfest-accepted

#216 Add Kaggle
  web_accounts_list.json
Labels: hacktoberfest-accepted

#217 Added TheTattooForum and Quora
  web_accounts_list.json
Labels: hacktoberfest-accepted

#219 Garmin is back working again so have changed it to valid
  web_accounts_list.json
Labels: hacktoberfest-accepted

#220 Add Ko-Fi
  web_accounts_list.json
Labels: hacktoberfest-accepted
